# Generated by Django 2.0.5 on 2018-08-24 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraries', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='likes',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='likes',
            field=models.ManyToManyField(related_name='itinerary_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
