# Generated by Django 2.0.5 on 2018-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_auto_20180824_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='accounts.Account'),
        ),
    ]
