language: python
python:
  - "3.6.3"
install: "pip install -r requirements.txt"
script:
 - SECRET_KEY="whatever" ./src/manage.py makemigrations
 - SECRET_KEY="whatever" ./src/manage.py migrate
 - SECRET_KEY="whatever" ./src/manage.py test