# Generated by Django 2.0.5 on 2018-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180825_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_from',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
