# Generated by Django 2.0.5 on 2018-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180825_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_from',
            new_name='location',
        ),
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
