# Generated by Django 2.0.5 on 2018-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_itinerary_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_phone_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='billing_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
